### ISSUE TITLE
Ai and Backend research

### ISSUE THREAD

**Issue by Nouran246** [Nouran246/Personalized-Recipe-Recommender#5]

**Comment by Ayo-J** [comment]
Project Architecture Overview
Frontend (React): Collect user input (ingredients, preferences) and display personalized recipe recommendations.
Backend (Node.js + Express): Handle API requests, interact with Azure Personalizer, and manage user data.
Database (MongoDB): Store user data, preferences, and interaction history for further personalization.
Azure Personalizer: Process user context and provide personalized recipe recommendations.

App Workflow Overview Without LUIS
User Input Collection:

Frontend (React): Create an input form where users can type in the ingredients they have and their dietary preferences.
Backend (Node.js + Express): Receive this input and process it for use with Azure Personalizer.
Integration with Azure Personalizer:

Send the user input (ingredients and preferences) as context to Azure Personalizer using an HTTP request.
Azure Personalizer uses this data to generate personalized recipe recommendations.
Processing and Displaying Recommendations:

Receive the personalized recommendations from Azure Personalizer in your backend.
Send the results back to the frontend to display to the user.

this is the workflow . 
![image](https://github.com/user-attachments/assets/c7060880-2849-48d1-b620-f482efa4ecee)
